version: "3"
services:
  postbox:
    container_name: postbox
    image: byunseob/postbox:latest
    environment:
      - SMTP=smtp.gmail.com
      - PASSWORD=YOUR_PASSWORD
      - ACCOUNT=YOUR_ACCOUNT
      - "UWSGI_PROCESSES=3"
      - "UWSGI_THREADS=5"
      - "UWSGI_HTTP=:80"
    ports:
      - "80:80"
    sysctls:
      net.core.somaxconn: 4084
    ulimits:
       nproc: 65536
       nofile:
         soft: 65536
         hard: 65536
    restart: always
